language: bash

sudo: required

services:
  - docker

script:
  - docker build --no-cache --build-arg FTP_USERNAME=$FTP_USERNAME --build-arg FTP_PASSWORD=$FTP_PASSWORD --build-arg FTP_HOSTNAME=$FTP_HOSTNAME -t scholzj/qpid-cpp-build:travis .

after_success:
  - ./trigger_travis.sh $TRAVIS_TOKEN "scholzj" "docker-qpid-cpp" $TRAVIS_BRANCH
